// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteManagement3.Data;

#nullable disable

namespace WasteManagement3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421134846_InitialCreate3")]
    partial class InitialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Collector", b =>
                {
                    b.Property<int>("CollectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectorID"));

                    b.Property<string>("CollectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollectorID");

                    b.ToTable("Collector");
                });

            modelBuilder.Entity("WasteManagement3.Models.GarageCheckin", b =>
                {
                    b.Property<int>("CheckinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckinID"));

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollectorID")
                        .HasColumnType("int");

                    b.Property<int>("TruckID")
                        .HasColumnType("int");

                    b.HasKey("CheckinID");

                    b.HasIndex("CollectorID");

                    b.HasIndex("TruckID");

                    b.ToTable("GarageCheckin");
                });

            modelBuilder.Entity("WasteManagement3.Models.Hotel", b =>
                {
                    b.Property<int>("HotelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelID"));

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelID");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("WasteManagement3.Models.Truck", b =>
                {
                    b.Property<int>("TruckID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TruckID"));

                    b.Property<string>("TruckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TruckID");

                    b.ToTable("Truck");
                });

            modelBuilder.Entity("WasteManagement3.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WasteManagement3.Models.WasteCollection", b =>
                {
                    b.Property<int>("WasteCollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WasteCollectionID"));

                    b.Property<int>("CollectorID")
                        .HasColumnType("int");

                    b.Property<string>("CollectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("TruckID")
                        .HasColumnType("int");

                    b.Property<string>("TruckName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WasteTypeID")
                        .HasColumnType("int");

                    b.Property<string>("WasteTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WasteCollectionID");

                    b.HasIndex("CollectorID");

                    b.HasIndex("HotelID");

                    b.HasIndex("TruckID");

                    b.HasIndex("WasteTypeID");

                    b.ToTable("WasteCollection");
                });

            modelBuilder.Entity("WasteManagement3.Models.WasteType", b =>
                {
                    b.Property<int>("WasteTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WasteTypeID"));

                    b.Property<string>("WasteTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WasteTypeID");

                    b.ToTable("WasteType");
                });

            modelBuilder.Entity("WasteManagement3.Models.WeeklyStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TotalQuantity")
                        .HasColumnType("float");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeeklyStats");
                });

            modelBuilder.Entity("WasteManagement3.Models.GarageCheckin", b =>
                {
                    b.HasOne("WasteManagement3.Models.Users", "Collector")
                        .WithMany()
                        .HasForeignKey("CollectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteManagement3.Models.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collector");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("WasteManagement3.Models.WasteCollection", b =>
                {
                    b.HasOne("Collector", "Collector")
                        .WithMany("WasteCollection")
                        .HasForeignKey("CollectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteManagement3.Models.Hotel", "Hotel")
                        .WithMany("WasteCollection")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteManagement3.Models.Truck", "Truck")
                        .WithMany("WasteCollection")
                        .HasForeignKey("TruckID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WasteManagement3.Models.WasteType", "WasteType")
                        .WithMany("WasteCollection")
                        .HasForeignKey("WasteTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collector");

                    b.Navigation("Hotel");

                    b.Navigation("Truck");

                    b.Navigation("WasteType");
                });

            modelBuilder.Entity("Collector", b =>
                {
                    b.Navigation("WasteCollection");
                });

            modelBuilder.Entity("WasteManagement3.Models.Hotel", b =>
                {
                    b.Navigation("WasteCollection");
                });

            modelBuilder.Entity("WasteManagement3.Models.Truck", b =>
                {
                    b.Navigation("WasteCollection");
                });

            modelBuilder.Entity("WasteManagement3.Models.WasteType", b =>
                {
                    b.Navigation("WasteCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
